name: Check EDBP Plugins
on:
  schedule:
    - cron: '0 15 * * *' # 日本時間 00:00
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 書き込み権限が必要
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process Plugins
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # これでghコマンドが動くようになります
        run: node process_plugins.js

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add readme.json plugin.json plugins.json
          git commit -m "chore: update plugin registries" || exit 0
          git push
